# Generated by Django 5.1.2 on 2024-10-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetinApp', '0002_processedtexts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProcessedTexts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField()),
            ],
        ),
    ]
