# Generated by Django 5.1.2 on 2024-12-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetinApp', '0003_userprocessedtexts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprocessedtexts',
            name='original_text',
        ),
        migrations.AddField(
            model_name='userprocessedtexts',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
